/**
 * Program for generating polygons.
 *
 * This file is part of Davor Penzar's master thesis programing.
 *
 * Usage:
 *     ./generate N n out
 * where:
 *     N   is the number of polygons to generate (at least 1),
 *     n   is the number of vertices of each polygon (at least 3),
 *     out is the path to the output file to print the coordinates of vertices.
 *
 * The polygons are generated by generating each coordinate uniformly randomly
 * and independently of others (except that it is checked if the edges cross).
 *
 * Each polygon is printed to the output file in its own line.  Each polygon is
 * formatted as
 *     x_0 y_0 x_1 y_1 ... x_n_minus_1 y_n_minus_1
 * where x_i denotes the x-coordinate of the i-th vertex and y_i denotes the
 * y-coordinate of the i-th vertex.  It is guaranteed that the polygons are of
 * diameter 1 (up to a numerical precision) and that they fit in the
 * [-1 / 2, 1 / 2] x [-1 / 2, 1 / 2] square in the plane.
 *
 * @author Davor Penzar <davor.penzar@gmail.com>
 * @version 1.0
 * @package polygon
 *
 */

/* Compile with mathematical constants from "math.h". */
#define _USE_MATH_DEFINES   1

/* Include standard library headers. */
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

/* Include package headers. */
#include "array.h"
#include "boolean.h"
#include "numeric.h"
#include "polygon.h"
#include "playground.h"

/* Define constants for maximal numbers of iterations. */
#define IN_ITER_MAX     1024U
#define OUT_ITER_MAX    1024U
#define ATTEMPT_MAX     1024U

int main (int argc, char** argv)
{
    /* DECLARATION OF CONSTANTS */

    /* Error message for an unknown environment error. */
    const char* const err_msg_env = "Unknown environment error.";

    /* Error message for the illegal number of additional arguments. */
    const char* const err_msg_argc =
        "Number of additional arguments must be 3: number of polygons, number "
            "of vertices, output file path.";

    /* Error message for the illegal number of polygons. */
    const char* const err_msg_np = "Number of polygons must be at least 1.";

    /* Error message for the illegal number of vertices. */
    const char* const err_msg_nv = "Number of vertices must be at least 3.";

    /* Error message for the memory allocation fail. */
    const char* const err_msg_mem = "Memory allocation fail.";

    /* Error message for the maximal attempts exceeded. */
    const char* const err_msg_att = "Maximal attempts exceeded.";

    /* Error message for output file opening fail. */
    const char* const err_msg_out = "Output file cannot be opened.";

    /* Format string for printing error messages. */
    const char* const format_err_msg = "%s\n";

    /* Mode of the output file to open. */
    const char* const file_open_mode = "wt";

    /* DECLARATION OF VARIABLES */

    /* Number of polygons. */
    size_t N;

    /* Expected number of vertices and true number of vertices. */
    size_t n;
    size_t n_true;

    /* Array of vertices. */
    real_t* P;

    /* Output file. */
    FILE* out;

    /* Iteration indices. */
    size_t i;
    size_t j;

    /* INITIALISATION OF VARIABLES */

    /* Number of polygons. */
    N = 0U;

    /* Expected number of vertices and true number of vertices. */
    n = 0U;
    n_true = 0U;

    /* Array of vertices. */
    P = (real_t*)(NULL);

    /* Output file. */
    out = (FILE*)(NULL);

    /* Iteration indices. */
    i = 0U;
    j = 0U;

    /* ALGORITHM */

    /* Set the seed for the pseudorandom number generator. */
    srand((unsigned int)time((time_t*)(NULL)));

    /* If the number of additional command line arguments is not 3, print the
     * error message and exit with a non-zero value. */
    if (!(argc == 4))
    {
        /* Print the error message. */
        fprintf(stderr, format_err_msg, err_msg_argc);

        /* Exit with a non-zero value. */
        exit(EXIT_FAILURE);
    }

    /* If `argv` is a null-pointer, print the error message and exit with a
     * non-zero value. */
    if (!argv)
    {
        /* Print the error message. */
        fprintf(stderr, format_err_msg, err_msg_env);

        /* Exit with a non-zero value. */
        exit(EXIT_FAILURE);
    }

    /* If any of the 4 command line arguments is a null-pointer, print the error
     * message and exit with a non-zero value. */
    if (!(*argv && *(argv + 1U) && *(argv + 2U) && *(argv + 3U)))
    {
        /* Print the error message. */
        fprintf(stderr, format_err_msg, err_msg_env);

        /* Exit with a non-zero value. */
        exit(EXIT_FAILURE);
    }

    /* Scan the number of polygons. */
    N = atoi(*(argv + 1U));

    /* Scan the number of vertces. */
    n = atoi(*(argv + 2U));

    /* If the number of polygons is 0, print the error message and exit with a
     * non-zero value. */
    if (!N)
    {
        /* Print the error message. */
        fprintf(stderr, format_err_msg, err_msg_np);

        /* Exit with a non-zero value. */
        exit(EXIT_FAILURE);
    }

    /* If the number of vertices is strictly less than 3, print the error
     * message and exit with a non-zero value. */
    if (n < 3U)
    {
        /* Print the error message. */
        fprintf(stderr, format_err_msg, err_msg_nv);

        /* Exit with a non-zero value. */
        exit(EXIT_FAILURE);
    }

    /* Allocate memory for the polygons. */
    P = (real_t*)malloc(((N * n) << 1U) * sizeof *P);

    /* If the memory allocation has failed, print the error message and exit
     * with a non-zero value. */
    if (!P)
    {
        /* Print the error message. */
        fprintf(stderr, format_err_msg, err_msg_mem);

        /* Exit with a non-zero value. */
        exit(EXIT_FAILURE);
    }

    /* Initialise coordinates of vertices of polygons to zeros. */
    memset(P, 0, ((N * n) << 1U) * sizeof *P);

    /* Save the number of vertices to the `saved_nn_integer` function. */
    saved_nn_integer(n);

    /* Generate `N` polygons. */
    for (i = 0U; i < N; ++i)
    {
        /* Try to generate the `i`-th polygon. */
        for (j = 0U; j < (ATTEMPT_MAX); ++j)
        {
            /* Set the value of number `n_true` to the value of `n`. */
            n_true = n;

            /* Generate an array of `n` points using the `smart_random_polygon`
             * function. */
            smart_random_polygon(
                n,
                P + ((i * n) << 1U),
                random_coordinate,
                OUT_ITER_MAX,
                IN_ITER_MAX
            );

            /* Reorder the vertices by flipping the array from index 2 to the
             * end. */
            flip(P + ((i * n) << 1U) + 2U, n - 1U, 2U * sizeof *P);

            /* Simplify and check the array for the polygon.  If the array
             * represents a true `n`-gon, break the `for`-loop. */
            if (simplify_check_polygon(&n_true, P + ((i * n) << 1U)))
                if (n_true == n)
                    break;

            /* Clear the memory in the array of points. */
            memset(P + ((i * n) << 1U), 0, (n << 1U) * sizeof *P);
        }

        /* If the maximal number of attempts was exceeded, print the error
         * message, deallocate memory and exit with a non-zero value. */
        if (j >= (ATTEMPT_MAX))
        {
            /* Print the error message. */
            fprintf(stderr, format_err_msg, err_msg_att);

            /* Clear the memory in the array of points. */
            memset(P, 0, ((N * n) << 1U) * sizeof *P);

            /* Deallocate memory for the polygons. */
            free(P);
            P = (real_t*)(NULL);

            /* Exit with a non-zero value. */
            exit(EXIT_FAILURE);
        }

        /* Normalise the `i`-th polygon. */
        normalise_polygon(n, P + ((i * n) << 1U));
    }

    /* Open the output file. */
    out = fopen(*(argv + 3U), file_open_mode);

    /* If the output file could not be opened, print the error message,
     * deallocate memory and exit with a non-zero value. */
    if (!out)
    {
        /* Print the error message. */
        fprintf(stderr, format_err_msg, err_msg_out);

        /* Clear the memory in the array of points. */
        memset(P, 0, ((N * n) << 1U) * sizeof *P);

        /* Deallocate memory for the polygons. */
        free(P);
        P = (real_t*)(NULL);

        /* Exit with a non-zero value. */
        exit(EXIT_FAILURE);
    }

    /* Dump the polygonst to the output file. */
    dump_polygons(out, n, P, N);

    /* Close the output file. */
    fclose(out);
    out = (FILE*)(NULL);

    /* Clear the memory in the array of points. */
    memset(P, 0, ((N * n) << 1U) * sizeof *P);

    /* Deallocate memory for the polygons. */
    free(P);
    P = (real_t*)(NULL);

    /* Return a zero value (exit with a zero value). */
    return EXIT_SUCCESS;
}
